version: '3.8'

services:
  nsfw-detector:
    build: .
    container_name: nsfw-detector
    ports:
      - "2002:2002"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    stdin_open: true